spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springReact
    username: postgres
    password: 3701
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql : true
    properties:
        format_sql : true

token:
    signing:
        key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855